# lightning.pytorch==2.0.2
seed_everything: true
trainer:
  accelerator: gpu
  strategy: deepspeed_stage_2_offload
  devices: 1
  num_nodes: 1
  precision: bf16
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: Echo-B-1B6 Foundation-enwiki-training
      save_dir: .
      version: null
      offline: false
      dir: null
      id: mgyx9u3k
      anonymous: null
      project: RWKV-Memory-Experiment
      log_model: false
      experiment: null
      prefix: ''
      checkpoint_name: null
      job_type: null
      config: null
      entity: null
      reinit: null
      tags:
      - RWKV
      - memory-exp
      group: null
      notes: null
      magic: null
      config_exclude_keys: null
      config_include_keys: null
      mode: null
      allow_val_change: null
      resume: true
      force: null
      tensorboard: null
      sync_tensorboard: null
      monitor_gym: null
      save_code: null
      settings: null
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: /home/picocreator/rwkv-proj/my-RWKV-LM-LoRA/checkpoint/echo-B-1B6/
      filename: null
      monitor: time_log
      verbose: false
      save_last: null
      save_top_k: 10
      save_weights_only: false
      mode: max
      auto_insert_metric_name: true
      every_n_train_steps: 10
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: true
  fast_dev_run: false
  max_epochs: 8
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 1
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 256
  gradient_clip_val: 1.0
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: true
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  ctx_len: 2048
  ctx_len_cutoffs:
  - 8192
  ctx_len_warmup_steps:
  - 0
  n_embd: 1536
  n_layer: 48
  vocab_size: 50277
  grad_cp: true
  lr_init: 0.001
  warmup_steps: -1
  beta1: 0.9
  beta2: 0.99
  adam_eps: 1.0e-08
  layerwise_lr: true
  dim_att: null
  dim_ffn: null
  load_model: /home/picocreator/rwkv-proj/my-RWKV-LM-LoRA/build/Echo-B-Init-1B6.pth
data:
  data_path: /home/picocreator/rwkv-proj/my-RWKV-LM-LoRA/data_path/
  source: text
  source_data_dir: ../dataset-text/
  test_split: 0.05
  test_split_shuffle: false
  text_chunk_size: 2048
  tokenizer: neox
  disablePromptCompletionMasking: false
ckpt_path: null
